export const SELECT_HEADER_USER = [
  { value: "Profile", label: "Profile" },
  { value: "Order", label: "Order" },
  { value: "SignOut", label: "Sign Out" },
];
export const SELECT_HEADER_ADMIN = [
  { value: "Profile", label: "Profile" },
  { value: "Order", label: "Order" },
  { value: "DashBoard", label: "DashBoard" },
  { value: "SignOut", label: "Sign Out" },
];
export const SELECT_COUNTRY = [
  { value: "united_states", label: "United States" },
  { value: "canada", label: "Canada" },
  { value: "mexico", label: "Mexico" },
  { value: "brazil", label: "Brazil" },
  { value: "argentina", label: "Argentina" },
  { value: "united_kingdom", label: "United Kingdom" },
  { value: "france", label: "France" },
  { value: "germany", label: "Germany" },
  { value: "italy", label: "Italy" },
  { value: "spain", label: "Spain" },
  { value: "russia", label: "Russia" },
  { value: "china", label: "China" },
  { value: "japan", label: "Japan" },
  { value: "south_korea", label: "South Korea" },
  { value: "india", label: "India" },
  { value: "australia", label: "Australia" },
  { value: "new_zealand", label: "New Zealand" },
  { value: "south_africa", label: "South Africa" },
  { value: "egypt", label: "Egypt" },
  { value: "nigeria", label: "Nigeria" },
  { value: "kenya", label: "Kenya" },
  { value: "israel", label: "Israel" },
  { value: "turkey", label: "Turkey" },
  { value: "saudi_arabia", label: "Saudi Arabia" },
  { value: "united_arab_emirates", label: "United Arab Emirates" },
  { value: "iran", label: "Iran" },
  { value: "indonesia", label: "Indonesia" },
  { value: "thailand", label: "Thailand" },
  { value: "vietnam", label: "Vietnam" },
  { value: "philippines", label: "Philippines" },
  { value: "malaysia", label: "Malaysia" },
  { value: "singapore", label: "Singapore" },
  { value: "pakistan", label: "Pakistan" },
  { value: "bangladesh", label: "Bangladesh" },
  { value: "ukraine", label: "Ukraine" },
  { value: "poland", label: "Poland" },
  { value: "netherlands", label: "Netherlands" },
  { value: "belgium", label: "Belgium" },
  { value: "sweden", label: "Sweden" },
  { value: "norway", label: "Norway" },
  { value: "denmark", label: "Denmark" },
  { value: "finland", label: "Finland" },
  { value: "switzerland", label: "Switzerland" },
  { value: "austria", label: "Austria" },
  { value: "greece", label: "Greece" },
  { value: "portugal", label: "Portugal" },
  { value: "ireland", label: "Ireland" },
  { value: "czech_republic", label: "Czech Republic" },
  { value: "hungary", label: "Hungary" },
];
